controllers:
    resource:
        path: ../src/UI/Controller/
        namespace: App\UI\Controller
    type: attribute

api_doc:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui
